
name: Workflow - Feature
on:
  push:
    branches:
      - 'feature/*'
jobs:
  print_hello_world:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v3
      - run : chmod +x gradlew
      - run : |
         gpg \
          -d \
          --batch \
          --passphrase "$(echo "${{ secrets.PASSWORD}}" | base64 --decode)" \
          "${{ secrets.KEYSTORE_P12}}"> "keystore.p12"
      - run: |
          gpg \
           -d \
           --batch \
           --passphrase "$(echo "${{ secrets.PASSWORD}}" | base64 --decode)" \
           "${{ secrets.KEYSTORE_PROPERTIES}}"> "keystore.properties"
      - run: |
          gpg \
           -d \
           --batch \
           --passphrase "$(echo "${{ secrets.PASSWORD}}" | base64 --decode)" \
             "${{ secrets.API_PRIVATEKEY_MARVEL}}"> "apimarvel.properties"

      - run: ./gradlew -Pversion.buildNumber="${GITHUB_RUN_NUMBER}" assembleDevelopmentDebug
      - uses: actions/upload-artifact@v3
        with:
          name: development-realease-apk
          path: app/build/outputs/apk/development/debug/app-development-debug.apk

